#region Using Statements
using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;
#endregion

namespace Delight
{
    /// <summary>
    /// Static class for accessing the application models. References to models added through partial classes generated by the framework.
    /// </summary>
    public static partial class Models
    {
        static Models()
        {
            // TODO lookup model bootstrappers and execute them
        }
    }
}
