#region Using Statements
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using UnityEngine;
using UnityEngine.UI;
#endregion

namespace Delight
{
    /// <summary>
    /// Main access point for all the assets used by the framework. 
    /// </summary>
    public static partial class Assets
    {
        #region Fields

        public static string AssetBundlesServerUri = AssetBundle.SimulatedUri;
        public static ServerUriLocator AssetBundlesServerUriLocator = new ServerUriLocator();

        #endregion
    }

    // The below code will be generated by the framework and put into Assets_g.cs:

    #region Asset Bundles

    /// <summary>
    /// Asset bundle data provider. Contains all the asset bundles used by the framework.
    /// </summary>
    public partial class AssetBundleData
    {
        #region Fields

        //public readonly AssetBundle Bundle1;
        //public readonly AssetBundle Bundle2;

        #endregion

        #region Constructor

        //public AssetBundleData()
        //{
        //    Bundle1 = new AssetBundle { Id = "Bundle1", StorageMode = StorageMode.Local };
        //    Bundle2 = new AssetBundle { Id = "Bundle2", StorageMode = StorageMode.Remote };

        //    Add(Bundle1);
        //    Add(Bundle2);
        //}

        #endregion
    }

    #endregion

    #region Sprites

    public partial class SpriteAsset : AssetObject<Sprite>
    {
    }

    public partial class SpriteAssetData : DataProvider<SpriteAsset>
    {
        //public readonly SpriteAsset Frame1;
        //public readonly SpriteAsset Frame2;
        //public readonly SpriteAsset Frame3;
        //public readonly SpriteAsset Frame4;
        //public readonly SpriteAsset BigSprite;

        //public SpriteAssets()
        //{
        //    Frame1 = new SpriteAsset { Id = "Frame1", AssetBundleId = "Bundle1" };
        //    Frame2 = new SpriteAsset { Id = "Frame2", AssetBundleId = "Bundle1" };
        //    Frame3 = new SpriteAsset { Id = "Frame3", AssetBundleId = "Bundle2" };
        //    Frame4 = new SpriteAsset { Id = "Frame4", IsResource = true };
        //    BigSprite = new SpriteAsset { Id = "BigSprite", AssetBundleId = "Bundle2" };

        //    Add(Frame1);
        //    Add(Frame2);
        //    Add(Frame3);
        //    Add(Frame4);
        //    Add(BigSprite);
        //}
    }

    public static partial class Assets
    {
        //public static SpriteAssetData Sprites = new SpriteAssetData();
    }

    #endregion
}
